### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by ANWANGJHU** [KChen-lab/marker-selection#5]
Hi! I am running SCMER on a single-cell dataset with 30000+ cells and 8000 genes with the function

`model = UmapL1(lasso=0.005, n_threads=16, use_gpu=True).fit(adata.X)`

Below is the error I receive. I wonder is there any solution (like setting some parameters) to prevent the memory overflow issue? I will hugely appreciate any help! Thank you in advance!!!!
(Remark: SCMER can be run on gpu with no issue on datasets less than 10000 cells. )

OutOfMemoryError: CUDA out of memory. Tried to allocate 14.02 GiB. GPU 0 has a total capacity of 23.99 GiB of which 0 bytes is free. Of the allocated memory 30.76 GiB is allocated by PyTorch, and 10.58 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e33c07f5-784e-464b-99e5-588d8fe82dd4) or open in a [text editor](command:workbench.action.openLargeOutput?e33c07f5-784e-464b-99e5-588d8fe82dd4). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by lshh125** [comment]
Thank you for using our tool and sorry for the late reply. 

You may have noticed the ''batch'' argument in `model.fit(adata.X, batches=adata.obs['batch'].values)`. (See https://scmer.readthedocs.io/en/latest/ileum-lamina-propria-immunocytes.html)

If your data already have some technical batches, great! Use that. Otherwise, you can randomly split your data into batches smaller than 10,000 cells (preferably < 5,000 to run faster). [However, DO NOT split your data by biologically meaningful labels like cell types.]

Let me know if it works. Thanks!

**Comment by ANWANGJHU** [comment]
Thank you! This indeed help! I just want to point out there is one very small mistake in the code. In code line 219 of _umap_l1.py, what you currently have is 

`X, P, beta = cls._resolve_batches(X_teacher, None, batches, n_pcs, perplexity, tictoc, verbose_print, n_threads)` 

which miss the argument "pca_seed"
